name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  scrollable_table_view: ^2.0.2
  flutter_svg: ^2.0.7
  slang: ^3.22.0
  slang_flutter: ^3.18.0
  theme_tailor: ^2.0.0
  theme_tailor_annotation: ^2.0.0
  go_router: ^10.0.0

  balanced_text: ^0.0.3


  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  get_it: ^7.6.0

  chopper: ^7.0.5
  chopper_generator: ^7.0.2

  source_gen: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  email_validator: ^2.1.17
  flutter_native_splash: ^2.3.2
  logger: ^2.0.2
  get_storage: ^2.1.1

  # google_nav_bar:

  nav_bar:
    path: ./nav_bar

  page_transition: "^2.1.0"

  # vibration: ^1.7.5
  # vibration_web: ^1.6.5
  
  top_snackbar_flutter: ^3.1.0
  # ai_barcode_scanner: ^0.0.7

  flutter_localizations:
    sdk: flutter
  file_picker: ^5.5.0
  animations: ^2.0.8
  dropdown_button2: ^3.0.0-beta.5
  flutter_login_yandex: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  